language: php
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- nightly
jobs:
  allow_failures:
  - php: nightly
before_script:
- composer require --dev phpunit/phpunit
- composer require --dev phpunit/php-code-coverage
- phpenv config-rm xdebug.ini
script:
- ./vendor/bin/phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd ..
- mkdir packages
- zip -r packages/tpl_ssstt_shiatsu.zip tpl_ssstt_shiatsu/src -x \*.git\*
- git clone -b 1.0.0 https://github.com/Gileba/plg_system_templatecompanion.git plg_system_templatecompanion
- cd plg_system_templatecompanion/src; zip -r ../../packages/plg_system_templatecompanion.zip * -x \*.git\* *.gitignore*; cd ../../
- cp tpl_ssstt_shiatsu/pkg_ssstt_shiatsu.xml pkg_ssstt_shiatsu.xml
- zip pkg_ssstt_shiatsu packages/tpl_ssstt_shiatsu.zip packages/plg_system_templatecompanion.zip pkg_ssstt_shiatsu.xml
deploy:
  provider: releases
  edge: true
  file:
  - packages/tpl_ssstt_shiatsu.zip
  - pkg_ssstt_shiatsu.zip
  on:
    tags: true
  api_key: $GITHUB_TOKEN
after_deploy: curl -T tpl_ssstt_shiatsu/tpl_ssstt_shiatsu.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
